import { ArrowUpRight, Folder, FolderGit2, FolderPlus, GitBranch, Pin, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { ProjectRecord } from '@/types/api'
import { formatRelative } from '@/lib/data'
import { EmptyState, IconButton, Modal } from '@/components/ui'
import { useI18n } from '@/lib/i18n'

export function ProjectsPage({ projects, onAdd, onOpen, onRemove }: { projects: ProjectRecord[]; onAdd(): void; onOpen(project: ProjectRecord): void; onRemove(project: ProjectRecord): void }) {
  const { t } = useI18n()
  const [query, setQuery] = useState('')
  const [removeTarget, setRemoveTarget] = useState<ProjectRecord | null>(null)
  const visible = useMemo(() => projects.filter((project) => `${project.name} ${project.path} ${project.gitBranch ?? ''}`.toLowerCase().includes(query.toLowerCase())), [projects, query])
  return <div className="page scroll-area"><div className="page-container"><header className="page-header"><div><h1>{t('nav.projects')}</h1><p>{t('page.projects.subtitle')}</p></div><button type="button" title={t('page.projects.addProject')} className="button button--primary" onClick={onAdd}><FolderPlus size={14}/> {t('page.projects.addProject')}</button></header><div className="page-tools"><label className="page-search"><Search size={14}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('page.projects.searchPlaceholder')}/></label><span>{t('page.projects.count', { count: visible.length })}</span></div>{visible.length ? <div className="project-library">{visible.map((project) => <article key={project.id} className="project-item"><button type="button" className="project-item__open" onClick={() => onOpen(project)}><span className="project-item__icon"><FolderGit2 size={19}/></span><span className="project-item__body"><span><h2>{project.name}</h2>{project.pinned ? <Pin size={11} fill="currentColor"/> : null}</span><span className="project-item__path">{project.path}</span><span className="project-item__meta"><span><GitBranch size={12}/>{project.gitBranch ?? t('page.projects.noRepository')}</span><span>{t('page.projects.sessionCount', { count: project.sessionCount })}</span><span>{t('page.projects.opened', { time: formatRelative(project.lastOpenedAt) })}</span></span></span></button><div className="project-item__actions"><IconButton label={t('page.projects.openName', { name: project.name })} onClick={() => onOpen(project)}><ArrowUpRight size={14}/></IconButton><IconButton label={t('page.projects.removeName', { name: project.name })} onClick={() => setRemoveTarget(project)}><Trash2 size={14}/></IconButton></div></article>)}</div> : <EmptyState icon={<Folder size={25}/>} title={query ? t('page.projects.emptyTitle.noMatch') : t('page.projects.emptyTitle.addFirst')}>{query ? t('page.projects.emptyBody.noMatch') : t('page.projects.emptyBody.addFirst')}</EmptyState>}{removeTarget ? <Modal title={t('page.projects.removeModal.title')} onClose={() => setRemoveTarget(null)} footer={<><button type="button" className="button" onClick={() => setRemoveTarget(null)}>{t('common.cancel')}</button><button type="button" className="button button--danger" onClick={() => { const project = removeTarget; setRemoveTarget(null); onRemove(project) }}>{t('common.remove')}</button></>}><p>{t('page.projects.removeModal.body', { name: removeTarget.name })}</p></Modal> : null}</div></div>
}
